name: pre-commit
run-name: ${{ github.actor }} is running a flow
on: [push]
jobs:
  my-job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: pre-commit/action@v3.0.0
